// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addreaction.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decrementPostHates = `-- name: DecrementPostHates :exec
UPDATE posts SET hates_count = GREATEST(0, hates_count - 1) WHERE id = $1
`

func (q *Queries) DecrementPostHates(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementPostHates, id)
	return err
}

const decrementPostLikes = `-- name: DecrementPostLikes :exec
UPDATE posts SET likes_count = GREATEST(0, likes_count - 1) WHERE id = $1
`

func (q *Queries) DecrementPostLikes(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementPostLikes, id)
	return err
}

const getPostReactionCountsLive = `-- name: GetPostReactionCountsLive :one

SELECT 
    COUNT(*) FILTER (WHERE reaction_type = 'LIKE') AS live_likes_count,
    COUNT(*) FILTER (WHERE reaction_type = 'HATE') AS live_hates_count
FROM post_reactions
WHERE post_id = $1
`

type GetPostReactionCountsLiveRow struct {
	LiveLikesCount int64
	LiveHatesCount int64
}

// ====================================================================================
// 3. كويريات العدادات وقوائم المستخدمين (Metrics & Users Lists)
// ====================================================================================
// جلب أرقام التفاعلات الحية مباشرة من جدول التفاعلات لغرض المطابقة الحية وضمان دقة البيانات
func (q *Queries) GetPostReactionCountsLive(ctx context.Context, postID int64) (GetPostReactionCountsLiveRow, error) {
	row := q.db.QueryRow(ctx, getPostReactionCountsLive, postID)
	var i GetPostReactionCountsLiveRow
	err := row.Scan(&i.LiveLikesCount, &i.LiveHatesCount)
	return i, err
}

const getPostWithReactionStatus = `-- name: GetPostWithReactionStatus :one
SELECT 
    p.id AS post_id,
    p.title,
    p.description,
    p.url,
    p.likes_count,
    p.hates_count,
    p.comments_count,
    p.shares_count,
    p.saves_count,
    p.point AS post_points,
    p.created_at AS post_created_at,
    u.id AS author_id,
    u.username AS author_username,
    u.name AS author_name,
    COALESCE(pr.reaction_type, '') AS current_user_reaction
FROM posts p
INNER JOIN users u ON p.user_id = u.id
LEFT JOIN post_reactions pr ON pr.post_id = p.id AND pr.user_id = $2
WHERE p.id = $1
`

type GetPostWithReactionStatusParams struct {
	ID     int64
	UserID int64
}

type GetPostWithReactionStatusRow struct {
	PostID              int64
	Title               string
	Description         string
	Url                 pgtype.Text
	LikesCount          pgtype.Int4
	HatesCount          pgtype.Int4
	CommentsCount       pgtype.Int4
	SharesCount         pgtype.Int4
	SavesCount          pgtype.Int4
	PostPoints          pgtype.Int4
	PostCreatedAt       pgtype.Timestamp
	AuthorID            int64
	AuthorUsername      string
	AuthorName          string
	CurrentUserReaction string
}

// كويري ضخم يجلب تفاصيل المنشور بالكامل، مع بيانات الكاتب (Author)،
// بالإضافة إلى حالة تفاعل المستخدم الحالي (هل وضع لايك أو هيت أم لم يتفاعل أصلاً) في طلب واحد ذكي.
func (q *Queries) GetPostWithReactionStatus(ctx context.Context, arg GetPostWithReactionStatusParams) (GetPostWithReactionStatusRow, error) {
	row := q.db.QueryRow(ctx, getPostWithReactionStatus, arg.ID, arg.UserID)
	var i GetPostWithReactionStatusRow
	err := row.Scan(
		&i.PostID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.LikesCount,
		&i.HatesCount,
		&i.CommentsCount,
		&i.SharesCount,
		&i.SavesCount,
		&i.PostPoints,
		&i.PostCreatedAt,
		&i.AuthorID,
		&i.AuthorUsername,
		&i.AuthorName,
		&i.CurrentUserReaction,
	)
	return i, err
}

const getReaction = `-- name: GetReaction :one
SELECT post_id, user_id, reaction_type, created_at
FROM post_reactions
WHERE post_id = $1 AND user_id = $2
`

type GetReactionParams struct {
	PostID int64
	UserID int64
}

// جلب تفاعل مستخدم محدد على منشور محدد
func (q *Queries) GetReaction(ctx context.Context, arg GetReactionParams) (PostReaction, error) {
	row := q.db.QueryRow(ctx, getReaction, arg.PostID, arg.UserID)
	var i PostReaction
	err := row.Scan(
		&i.PostID,
		&i.UserID,
		&i.ReactionType,
		&i.CreatedAt,
	)
	return i, err
}

const getReactionsForFeedByPostIDs = `-- name: GetReactionsForFeedByPostIDs :many

SELECT post_id, reaction_type
FROM post_reactions
WHERE user_id = $1 
AND post_id = ANY($2::bigint[])
`

type GetReactionsForFeedByPostIDsParams struct {
	UserID  int64
	Column2 []int64
}

type GetReactionsForFeedByPostIDsRow struct {
	PostID       int64
	ReactionType string
}

// ====================================================================================
// 2. كويريات جلب البيانات المتقدمة والخلاصة (Feed & Batch Operations)
// ====================================================================================
// كويري جوهري للـ Feed: يمرر له مصفوفة من أرقام المنشورات ومعرف المستخدم الحالي،
// فيجلب لك كل تفاعلات المستخدم عليها بطلب واحد فقط من قاعدة البيانات لتلوين الأزرار في الواجهة.
func (q *Queries) GetReactionsForFeedByPostIDs(ctx context.Context, arg GetReactionsForFeedByPostIDsParams) ([]GetReactionsForFeedByPostIDsRow, error) {
	rows, err := q.db.Query(ctx, getReactionsForFeedByPostIDs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReactionsForFeedByPostIDsRow
	for rows.Next() {
		var i GetReactionsForFeedByPostIDsRow
		if err := rows.Scan(&i.PostID, &i.ReactionType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPostHates = `-- name: IncrementPostHates :exec
UPDATE posts SET hates_count = hates_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostHates(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementPostHates, id)
	return err
}

const incrementPostLikes = `-- name: IncrementPostLikes :exec

UPDATE posts SET likes_count = likes_count + 1 WHERE id = $1
`

// ====================================================================================
// 4. كويريات المزامنة والتحديث الذري للعدادات (Atomic Counters Synchronization)
// ====================================================================================
func (q *Queries) IncrementPostLikes(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementPostLikes, id)
	return err
}

const listUsersWhoReacted = `-- name: ListUsersWhoReacted :many
SELECT 
    u.id AS user_id,
    u.username,
    u.name,
    u.city,
    pr.reaction_type,
    pr.created_at AS reacted_at
FROM post_reactions pr
INNER JOIN users u ON pr.user_id = u.id
WHERE pr.post_id = $1 
AND ($2::varchar = '' OR pr.reaction_type = $2)
ORDER BY pr.created_at DESC
LIMIT $3 OFFSET $4
`

type ListUsersWhoReactedParams struct {
	PostID  int64
	Column2 string
	Limit   int32
	Offset  int32
}

type ListUsersWhoReactedRow struct {
	UserID       int64
	Username     string
	Name         string
	City         pgtype.Text
	ReactionType string
	ReactedAt    pgtype.Timestamp
}

// جلب قائمة المستخدمين الذين تفاعلوا مع منشور معين (مثلاً لمعرفة من ضغط لايك)،
// مصفية حسب نوع التفاعل ومع دعم كامل للتصفح وعرض البيانات (Pagination) عبر Limit و Offset.
func (q *Queries) ListUsersWhoReacted(ctx context.Context, arg ListUsersWhoReactedParams) ([]ListUsersWhoReactedRow, error) {
	rows, err := q.db.Query(ctx, listUsersWhoReacted,
		arg.PostID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWhoReactedRow
	for rows.Next() {
		var i ListUsersWhoReactedRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Name,
			&i.City,
			&i.ReactionType,
			&i.ReactedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE FROM post_reactions
WHERE post_id = $1
AND user_id = $2
`

type RemoveReactionParams struct {
	PostID int64
	UserID int64
}

// حذف التفاعل نهائياً عند إلغائه
func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.Exec(ctx, removeReaction, arg.PostID, arg.UserID)
	return err
}

const syncPostCounters = `-- name: SyncPostCounters :exec
UPDATE posts p
SET 
    likes_count = (SELECT COUNT(*) FROM post_reactions WHERE post_id = p.id AND reaction_type = 'LIKE'),
    hates_count = (SELECT COUNT(*) FROM post_reactions WHERE post_id = p.id AND reaction_type = 'HATE')
WHERE p.id = $1
`

// كويري طوارئ/صيانة: يقوم بإعادة حساب كافة التفاعلات وتحديث جدول المنشورات تلقائياً لمنع أي تضارب بالعدادات الكاش
func (q *Queries) SyncPostCounters(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, syncPostCounters, id)
	return err
}

const upsertReaction = `-- name: UpsertReaction :one

INSERT INTO post_reactions (
    post_id,
    user_id,
    reaction_type
)
VALUES ($1, $2, $3)
ON CONFLICT (post_id, user_id) 
DO UPDATE SET reaction_type = EXCLUDED.reaction_type
RETURNING post_id, user_id, reaction_type, created_at
`

type UpsertReactionParams struct {
	PostID       int64
	UserID       int64
	ReactionType string
}

// ====================================================================================
// 1. العمليات الأساسية للتفاعل (Core Reaction CRUD)
// ====================================================================================
// إضافة تفاعل أو تحديثه تلقائياً إذا كان موجوداً مسبقاً (حل مشكلة الـ Conflict)
func (q *Queries) UpsertReaction(ctx context.Context, arg UpsertReactionParams) (PostReaction, error) {
	row := q.db.QueryRow(ctx, upsertReaction, arg.PostID, arg.UserID, arg.ReactionType)
	var i PostReaction
	err := row.Scan(
		&i.PostID,
		&i.UserID,
		&i.ReactionType,
		&i.CreatedAt,
	)
	return i, err
}
