// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchGetCommentsByIDs = `-- name: BatchGetCommentsByIDs :many
SELECT 
    c.id AS comment_id, 
    c.post_id, 
    c.content, 
    c.created_at,
    u.id AS author_id, 
    u.username AS author_username, 
    u.name AS author_name
FROM comments c
INNER JOIN users u ON c.user_id = u.id
WHERE c.id = ANY($1::bigint[])
ORDER BY ARRAY_POSITION($1::bigint[], c.id)
`

type BatchGetCommentsByIDsRow struct {
	CommentID      int64
	PostID         int64
	Content        string
	CreatedAt      pgtype.Timestamp
	AuthorID       int64
	AuthorUsername string
	AuthorName     string
}

// كويري عالي الأداء لتمرير مصفوفة IDs من التعليقات وجلبها كاملة بطلب واحد
func (q *Queries) BatchGetCommentsByIDs(ctx context.Context, dollar_1 []int64) ([]BatchGetCommentsByIDsRow, error) {
	rows, err := q.db.Query(ctx, batchGetCommentsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchGetCommentsByIDsRow
	for rows.Next() {
		var i BatchGetCommentsByIDsRow
		if err := rows.Scan(
			&i.CommentID,
			&i.PostID,
			&i.Content,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCommentsByPostID = `-- name: CountCommentsByPostID :one

SELECT COUNT(*)::bigint
FROM comments
WHERE post_id = $1
`

// ====================================================================================
// 3. العمليات الجماعية والإحصائيات (Batch Operations & Analytics Counters)
// ====================================================================================
// حساب إجمالي عدد التعليقات على منشور معين
func (q *Queries) CountCommentsByPostID(ctx context.Context, postID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByPostID, postID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createComment = `-- name: CreateComment :one

INSERT INTO comments (
    post_id,
    user_id,
    content
) VALUES (
    $1,
    $2,
    TRIM($3) -- حماية: إزالة الفراغات الزائدة من بداية ونهاية نص التعليق
)
RETURNING id, post_id, user_id, content, created_at
`

type CreateCommentParams struct {
	PostID int64
	UserID int64
	Btrim  string
}

// ====================================================================================
// 1. العمليات الأساسية وإدارة التعليقات بضوابط أمنية (Secure Comments CRUD)
// ====================================================================================
// إضافة تعليق جديد على منشور محدد مع إرجاع كامل البيانات فوراً (مفيدة لبث التعليق لحظياً عبر الـ WebSockets)
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.PostID, arg.UserID, arg.Btrim)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCommentSecure = `-- name: DeleteCommentSecure :exec
DELETE FROM comments
WHERE comments.id = $1 
  AND (
    comments.user_id = $2 
    OR comments.post_id IN (SELECT posts.id FROM posts WHERE posts.user_id = $2)
  )
`

type DeleteCommentSecureParams struct {
	ID     int64
	UserID int64
}

// هندسة أمنية متطورة للحذف (Secure Double-Check Delete):
// يُسمح بحذف التعليق في حالتين فقط:
// 1. أن يكون المستخدم ($2) هو الكاتب الفعلي للتعليق (user_id = $2).
// 2. أو أن يكون المستخدم ($2) هو صاحب المنشور الأصلي الذي كُتب عليه التعليق.
func (q *Queries) DeleteCommentSecure(ctx context.Context, arg DeleteCommentSecureParams) error {
	_, err := q.db.Exec(ctx, deleteCommentSecure, arg.ID, arg.UserID)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, post_id, user_id, content, created_at
FROM comments
WHERE id = $1
`

// جلب تفاصيل تعليق واحد محدد بواسطة الـ ID الخاص به
func (q *Queries) GetCommentByID(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listPostCommentsDetailed = `-- name: ListPostCommentsDetailed :many

SELECT 
    c.id AS comment_id,
    c.post_id,
    c.content AS comment_content,
    c.created_at AS comment_created_at,
    u.id AS author_id,
    u.username AS author_username,
    u.name AS author_name
FROM comments c
INNER JOIN users u ON c.user_id = u.id
WHERE c.post_id = $1
  AND ($2::bigint = 0 OR c.id > $2) -- استخدام c.id بشكل صريح يمنع الـ ambiguity تماماً
ORDER BY c.id ASC
LIMIT $3
`

type ListPostCommentsDetailedParams struct {
	PostID  int64
	Column2 int64
	Limit   int32
}

type ListPostCommentsDetailedRow struct {
	CommentID        int64
	PostID           int64
	CommentContent   string
	CommentCreatedAt pgtype.Timestamp
	AuthorID         int64
	AuthorUsername   string
	AuthorName       string
}

// ====================================================================================
// 2. جلب وتصفح قائمة التعليقات المتقدمة (Advanced Feed & Cursor Pagination)
// ====================================================================================
// الكويري الأساسي لعرض التعليقات تحت المنشور:
// يجلب التعليقات مدمجة (JOIN) مع بيانات كاتب التعليق لتجنب الطلبات المتكررة.
func (q *Queries) ListPostCommentsDetailed(ctx context.Context, arg ListPostCommentsDetailedParams) ([]ListPostCommentsDetailedRow, error) {
	rows, err := q.db.Query(ctx, listPostCommentsDetailed, arg.PostID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostCommentsDetailedRow
	for rows.Next() {
		var i ListPostCommentsDetailedRow
		if err := rows.Scan(
			&i.CommentID,
			&i.PostID,
			&i.CommentContent,
			&i.CommentCreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCommentsInPost = `-- name: SearchCommentsInPost :many
SELECT 
    c.id AS comment_id,
    c.post_id,
    c.content AS comment_content,
    c.created_at AS comment_created_at,
    u.id AS author_id,
    u.username AS author_username,
    u.name AS author_name
FROM comments c
INNER JOIN users u ON c.user_id = u.id
WHERE c.post_id = $1
  AND c.content ILIKE '%' || $2 || '%'
ORDER BY c.id DESC
LIMIT $3 OFFSET $4
`

type SearchCommentsInPostParams struct {
	PostID  int64
	Column2 pgtype.Text
	Limit   int32
	Offset  int32
}

type SearchCommentsInPostRow struct {
	CommentID        int64
	PostID           int64
	CommentContent   string
	CommentCreatedAt pgtype.Timestamp
	AuthorID         int64
	AuthorUsername   string
	AuthorName       string
}

// ميزة بحث متقدمة داخل تعليقات منشور محدد فقط، مع جلب بيانات كتابها ودعم الـ Pagination
func (q *Queries) SearchCommentsInPost(ctx context.Context, arg SearchCommentsInPostParams) ([]SearchCommentsInPostRow, error) {
	rows, err := q.db.Query(ctx, searchCommentsInPost,
		arg.PostID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCommentsInPostRow
	for rows.Next() {
		var i SearchCommentsInPostRow
		if err := rows.Scan(
			&i.CommentID,
			&i.PostID,
			&i.CommentContent,
			&i.CommentCreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommentSecure = `-- name: UpdateCommentSecure :one
UPDATE comments
SET content = TRIM($3)
WHERE id = $1 AND user_id = $2
RETURNING id, post_id, user_id, content, created_at
`

type UpdateCommentSecureParams struct {
	ID     int64
	UserID int64
	Btrim  string
}

// ميزة تعديل التعليق (Edit Comment): قيد أمان صارم جداً يمنع التعديل إلا إذا كان المستخدم الحالي ($2) هو الكاتب الفعلي للتعليق
func (q *Queries) UpdateCommentSecure(ctx context.Context, arg UpdateCommentSecureParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateCommentSecure, arg.ID, arg.UserID, arg.Btrim)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
