// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createmessage.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadMessagesInRoom = `-- name: CountUnreadMessagesInRoom :one
SELECT COUNT(*)::bigint
FROM private_messages
WHERE room_id = $1
  AND sender_id != $2
  AND is_read = FALSE
`

type CountUnreadMessagesInRoomParams struct {
	RoomID   int64
	SenderID int64
}

// حساب عدد الرسائل غير المقروءة الموجهة للمستخدم الحالي ($2) داخل غرفة محددة ($1)
// (يُستخدم لعرض رقم الإشعار الأحمر الصغير بجانب اسم الصديق في قائمة المحادثات)
func (q *Queries) CountUnreadMessagesInRoom(ctx context.Context, arg CountUnreadMessagesInRoomParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadMessagesInRoom, arg.RoomID, arg.SenderID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteMessageSecure = `-- name: DeleteMessageSecure :exec
DELETE FROM private_messages
WHERE id = $1 AND sender_id = $2
`

type DeleteMessageSecureParams struct {
	ID       int64
	SenderID int64
}

// ميزة التراجع عن الإرسال (Unsend/Delete Message): قيد أمان صارم يمنع أي مستخدم من حذف رسالة لم يقم هو بإرسالها بنفسه
func (q *Queries) DeleteMessageSecure(ctx context.Context, arg DeleteMessageSecureParams) error {
	_, err := q.db.Exec(ctx, deleteMessageSecure, arg.ID, arg.SenderID)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, room_id, sender_id, message_text, is_read, created_at
FROM private_messages
WHERE id = $1
`

// جلب تفاصيل رسالة واحدة محددة (مفيدة لمعالجة خلفية إشعارات الـ Push Notifications)
func (q *Queries) GetMessageByID(ctx context.Context, id int64) (PrivateMessage, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i PrivateMessage
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.MessageText,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomLatestMessagePreview = `-- name: GetRoomLatestMessagePreview :one

SELECT 
    pm.id AS message_id, pm.room_id, pm.message_text, pm.is_read, pm.created_at,
    u.id AS sender_id, u.username AS sender_username, u.name AS sender_name
FROM private_messages pm
INNER JOIN users u ON pm.sender_id = u.id
WHERE pm.room_id = $1
ORDER BY pm.id DESC
LIMIT 1
`

type GetRoomLatestMessagePreviewRow struct {
	MessageID      int64
	RoomID         int64
	MessageText    string
	IsRead         pgtype.Bool
	CreatedAt      pgtype.Timestamp
	SenderID       int64
	SenderUsername string
	SenderName     string
}

// ====================================================================================
// 4. معاينات وتحديثات قائمة صندوق الوارد (Inbox Previews)
// ====================================================================================
// كويري القائمة الرئيسية (Inbox Preview): يجلب أحدث رسالة أرسلت في الغرفة (نصها، وقتها، حالة قراءتها، واسم مرسلها)
// لعرضها تحت اسم المستخدم في القائمة الجانبية للتطبيق مثل تطبيقات المراسلة العالمية
func (q *Queries) GetRoomLatestMessagePreview(ctx context.Context, roomID int64) (GetRoomLatestMessagePreviewRow, error) {
	row := q.db.QueryRow(ctx, getRoomLatestMessagePreview, roomID)
	var i GetRoomLatestMessagePreviewRow
	err := row.Scan(
		&i.MessageID,
		&i.RoomID,
		&i.MessageText,
		&i.IsRead,
		&i.CreatedAt,
		&i.SenderID,
		&i.SenderUsername,
		&i.SenderName,
	)
	return i, err
}

const listRoomMessagesWithCursor = `-- name: ListRoomMessagesWithCursor :many

SELECT 
    pm.id AS message_id, pm.room_id, pm.message_text, pm.is_read, pm.created_at AS message_time,
    u.id AS sender_id, u.username AS sender_username, u.name AS sender_name
FROM private_messages pm
INNER JOIN users u ON pm.sender_id = u.id
WHERE pm.room_id = $1
  AND ($2::bigint = 0 OR pm.id < $2) -- إذا مررنا 0 يجلب الأحدث، وإذا مررنا ID يجلب الرسائل الأقدم منه (Scroll Up)
ORDER BY pm.id DESC
LIMIT $3
`

type ListRoomMessagesWithCursorParams struct {
	RoomID  int64
	Column2 int64
	Limit   int32
}

type ListRoomMessagesWithCursorRow struct {
	MessageID      int64
	RoomID         int64
	MessageText    string
	IsRead         pgtype.Bool
	MessageTime    pgtype.Timestamp
	SenderID       int64
	SenderUsername string
	SenderName     string
}

// ====================================================================================
// 2. جلب سجل المحادثات المتطور والبحث (Cursor Pagination & Chat History)
// ====================================================================================
// كويري شاشة المحادثة الذهبي (Cursor-Based Pagination):
// في تطبيقات الشات الاحترافية، لا نستخدم OFFSET لأنه يتسبب بتكرار الرسائل أو إسقاطها عند وصول رسائل جديدة أثناء التمرير.
// هنا نستخدم معرف الرسالة (Message ID) كمؤشر لجلب الرسائل الأقدم تصاعدياً، مدمجة (JOIN) مع بيانات المرسل لتقليل طلبات قاعدة البيانات.
func (q *Queries) ListRoomMessagesWithCursor(ctx context.Context, arg ListRoomMessagesWithCursorParams) ([]ListRoomMessagesWithCursorRow, error) {
	rows, err := q.db.Query(ctx, listRoomMessagesWithCursor, arg.RoomID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomMessagesWithCursorRow
	for rows.Next() {
		var i ListRoomMessagesWithCursorRow
		if err := rows.Scan(
			&i.MessageID,
			&i.RoomID,
			&i.MessageText,
			&i.IsRead,
			&i.MessageTime,
			&i.SenderID,
			&i.SenderUsername,
			&i.SenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllRoomMessagesAsRead = `-- name: MarkAllRoomMessagesAsRead :exec

UPDATE private_messages
SET is_read = TRUE
WHERE room_id = $1 
  AND sender_id != $2 
  AND is_read = FALSE
`

type MarkAllRoomMessagesAsReadParams struct {
	RoomID   int64
	SenderID int64
}

// ====================================================================================
// 3. إدارة حالات القراءة والعدادات (Read Receipts & Inbox Badges)
// ====================================================================================
// كويري تحديث حالة القراءة الذكي: بمجرد دخول المستخدم ($2) إلى الغرفة ($1)، تتحول جميع الرسائل الواردة إليه إلى "مقروءة".
// الكويري يستثني تلقائياً الرسائل التي قام المستخدم بإرسالها بنفسه (sender_id != $2) لضمان عدم تلاعب النظام بالبيانات.
func (q *Queries) MarkAllRoomMessagesAsRead(ctx context.Context, arg MarkAllRoomMessagesAsReadParams) error {
	_, err := q.db.Exec(ctx, markAllRoomMessagesAsRead, arg.RoomID, arg.SenderID)
	return err
}

const markMultipleMessagesAsRead = `-- name: MarkMultipleMessagesAsRead :exec
UPDATE private_messages
SET is_read = TRUE
WHERE id = ANY($1::bigint[]) 
  AND sender_id != $2
`

type MarkMultipleMessagesAsReadParams struct {
	Column1  []int64
	SenderID int64
}

// تحديث الدفعات الجماعية (Batch Update): تحويل مصفوفة من معرفات الرسائل إلى "مقروءة" بطلب واحد عالي الكفاءة
func (q *Queries) MarkMultipleMessagesAsRead(ctx context.Context, arg MarkMultipleMessagesAsReadParams) error {
	_, err := q.db.Exec(ctx, markMultipleMessagesAsRead, arg.Column1, arg.SenderID)
	return err
}

const searchMessagesInRoom = `-- name: SearchMessagesInRoom :many
SELECT 
    pm.id AS message_id, pm.room_id, pm.message_text, pm.is_read, pm.created_at AS message_time,
    u.id AS sender_id, u.username AS sender_username, u.name AS sender_name
FROM private_messages pm
INNER JOIN users u ON pm.sender_id = u.id
WHERE pm.room_id = $1 
  AND pm.message_text ILIKE '%' || $2 || '%'
ORDER BY pm.id DESC
LIMIT $3 OFFSET $4
`

type SearchMessagesInRoomParams struct {
	RoomID  int64
	Column2 pgtype.Text
	Limit   int32
	Offset  int32
}

type SearchMessagesInRoomRow struct {
	MessageID      int64
	RoomID         int64
	MessageText    string
	IsRead         pgtype.Bool
	MessageTime    pgtype.Timestamp
	SenderID       int64
	SenderUsername string
	SenderName     string
}

// ميزة البحث الاحترافي: البحث النصي الذكي (Fuzzy Search) داخل غرفة محادثة معينة فقط،
// لتمكين المستخدم من العثور على كلمة معينة في أرشيف الشات مع دعم الـ Pagination
func (q *Queries) SearchMessagesInRoom(ctx context.Context, arg SearchMessagesInRoomParams) ([]SearchMessagesInRoomRow, error) {
	rows, err := q.db.Query(ctx, searchMessagesInRoom,
		arg.RoomID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMessagesInRoomRow
	for rows.Next() {
		var i SearchMessagesInRoomRow
		if err := rows.Scan(
			&i.MessageID,
			&i.RoomID,
			&i.MessageText,
			&i.IsRead,
			&i.MessageTime,
			&i.SenderID,
			&i.SenderUsername,
			&i.SenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendMessage = `-- name: SendMessage :one

INSERT INTO private_messages (
    room_id,
    sender_id,
    message_text
) VALUES ($1, $2, TRIM($3))
RETURNING id, room_id, sender_id, message_text, is_read, created_at
`

type SendMessageParams struct {
	RoomID   int64
	SenderID int64
	Btrim    string
}

// ====================================================================================
// 1. عمليات إرسال وتعديل وحذف الرسائل بضوابط أمنية (Secure Messaging CRUD)
// ====================================================================================
// إرسال رسالة جديدة وإرجاع كامل بياناتها فوراً (تُستدعى داخل الـ WebSocket Handler لبثها للطرف الآخر)
func (q *Queries) SendMessage(ctx context.Context, arg SendMessageParams) (PrivateMessage, error) {
	row := q.db.QueryRow(ctx, sendMessage, arg.RoomID, arg.SenderID, arg.Btrim)
	var i PrivateMessage
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.MessageText,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const updateMessageSecure = `-- name: UpdateMessageSecure :one
UPDATE private_messages
SET message_text = TRIM($3)
WHERE id = $1 AND sender_id = $2
RETURNING id, room_id, sender_id, message_text, is_read, created_at
`

type UpdateMessageSecureParams struct {
	ID       int64
	SenderID int64
	Btrim    string
}

// ميزة تعديل الرسالة (Edit Message): قيد أمان يمنع التعديل إلا من المرسل الفعلي ($2) مع إرجاع البيانات المحدثة
func (q *Queries) UpdateMessageSecure(ctx context.Context, arg UpdateMessageSecureParams) (PrivateMessage, error) {
	row := q.db.QueryRow(ctx, updateMessageSecure, arg.ID, arg.SenderID, arg.Btrim)
	var i PrivateMessage
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.MessageText,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}
