// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: followuser.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkFollowStatus = `-- name: CheckFollowStatus :one
SELECT EXISTS (
    SELECT 1 FROM follows
    WHERE follower_id = $1::bigint AND following_id = $2::bigint
)::boolean AS is_following
`

type CheckFollowStatusParams struct {
	Column1 int64
	Column2 int64
}

// التحقق من حالة المتابعة (هل المستخدم أ يتابع المستخدم ب؟)
func (q *Queries) CheckFollowStatus(ctx context.Context, arg CheckFollowStatusParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkFollowStatus, arg.Column1, arg.Column2)
	var is_following bool
	err := row.Scan(&is_following)
	return is_following, err
}

const discoverPeopleToFollow = `-- name: DiscoverPeopleToFollow :many
SELECT 
    u.id AS recommended_user_id,
    u.username,
    u.name,
    u.description,
    COUNT(f2.follower_id)::bigint AS mutual_followers_count
FROM follows f1
INNER JOIN follows f2 ON f1.following_id = f2.follower_id
INNER JOIN users u ON f2.following_id = u.id
WHERE f1.follower_id = $1::bigint
  AND u.id != $1::bigint
  AND NOT EXISTS (
      SELECT 1 FROM follows f3
      WHERE f3.follower_id = $1::bigint AND f3.following_id = u.id
  )
GROUP BY u.id, u.username, u.name, u.description, u.followers
ORDER BY mutual_followers_count DESC, u.followers DESC
LIMIT $2::int OFFSET $3::int
`

type DiscoverPeopleToFollowParams struct {
	Column1 int64
	Column2 int32
	Column3 int32
}

type DiscoverPeopleToFollowRow struct {
	RecommendedUserID    int64
	Username             string
	Name                 string
	Description          pgtype.Text
	MutualFollowersCount int64
}

// محرك الاقتراحات الذكي للمنصة (اقتراح أصدقاء الأصدقاء بناءً على المتابعين المشتركين)
func (q *Queries) DiscoverPeopleToFollow(ctx context.Context, arg DiscoverPeopleToFollowParams) ([]DiscoverPeopleToFollowRow, error) {
	rows, err := q.db.Query(ctx, discoverPeopleToFollow, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverPeopleToFollowRow
	for rows.Next() {
		var i DiscoverPeopleToFollowRow
		if err := rows.Scan(
			&i.RecommendedUserID,
			&i.Username,
			&i.Name,
			&i.Description,
			&i.MutualFollowersCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const followUser = `-- name: FollowUser :exec

INSERT INTO follows (follower_id, following_id, created_at)
VALUES ($1::bigint, $2::bigint, NOW())
ON CONFLICT (follower_id, following_id) DO NOTHING
`

type FollowUserParams struct {
	Column1 int64
	Column2 int64
}

// ==========================================
// اسم الملف: followuser.sql
// الوصف: جميع استعلامات نظام المتابعة واكتشاف المستخدمين
// ==========================================
// عملية متابعة مستخدم جديد (تمنع التكرار بفضل ON CONFLICT)
func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.Column1, arg.Column2)
	return err
}

const getFollowCounters = `-- name: GetFollowCounters :one
SELECT 
    (SELECT COUNT(*)::bigint FROM follows WHERE follower_id = $1::bigint) AS following_count,
    (SELECT COUNT(*)::bigint FROM follows WHERE following_id = $1::bigint) AS followers_count
`

type GetFollowCountersRow struct {
	FollowingCount int64
	FollowersCount int64
}

// حساب أعداد المتابِعين والمتابَعين بشكل ديناميكي ودقيق للمستخدم
func (q *Queries) GetFollowCounters(ctx context.Context, dollar_1 int64) (GetFollowCountersRow, error) {
	row := q.db.QueryRow(ctx, getFollowCounters, dollar_1)
	var i GetFollowCountersRow
	err := row.Scan(&i.FollowingCount, &i.FollowersCount)
	return i, err
}

const getFollowersList = `-- name: GetFollowersList :many
SELECT 
    u.id AS user_id,
    u.username,
    u.name,
    u.description,
    u.followers AS total_followers,
    f.created_at AS followed_at
FROM follows f
INNER JOIN users u ON f.follower_id = u.id
WHERE f.following_id = $1::bigint
ORDER BY f.created_at DESC
LIMIT $2::int OFFSET $3::int
`

type GetFollowersListParams struct {
	Column1 int64
	Column2 int32
	Column3 int32
}

type GetFollowersListRow struct {
	UserID         int64
	Username       string
	Name           string
	Description    pgtype.Text
	TotalFollowers pgtype.Int4
	FollowedAt     pgtype.Timestamp
}

// جلب قائمة المتابِعين (الأشخاص الذين يتابعون مستخدماً معيناً) مع دعم الترقيم الصفحي
func (q *Queries) GetFollowersList(ctx context.Context, arg GetFollowersListParams) ([]GetFollowersListRow, error) {
	rows, err := q.db.Query(ctx, getFollowersList, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowersListRow
	for rows.Next() {
		var i GetFollowersListRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Name,
			&i.Description,
			&i.TotalFollowers,
			&i.FollowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingList = `-- name: GetFollowingList :many
SELECT 
    u.id AS user_id,
    u.username,
    u.name,
    u.description,
    u.followers AS total_followers,
    f.created_at AS followed_at
FROM follows f
INNER JOIN users u ON f.following_id = u.id
WHERE f.follower_id = $1::bigint
ORDER BY f.created_at DESC
LIMIT $2::int OFFSET $3::int
`

type GetFollowingListParams struct {
	Column1 int64
	Column2 int32
	Column3 int32
}

type GetFollowingListRow struct {
	UserID         int64
	Username       string
	Name           string
	Description    pgtype.Text
	TotalFollowers pgtype.Int4
	FollowedAt     pgtype.Timestamp
}

// جلب قائمة المتابَعين (الأشخاص الذين يقوم هذا المستخدم بمتابعتهم) مع دعم الترقيم الصفحي
func (q *Queries) GetFollowingList(ctx context.Context, arg GetFollowingListParams) ([]GetFollowingListRow, error) {
	rows, err := q.db.Query(ctx, getFollowingList, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowingListRow
	for rows.Next() {
		var i GetFollowingListRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Name,
			&i.Description,
			&i.TotalFollowers,
			&i.FollowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows
WHERE follower_id = $1::bigint AND following_id = $2::bigint
`

type UnfollowUserParams struct {
	Column1 int64
	Column2 int64
}

// إلغاء متابعة مستخدم
func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.Column1, arg.Column2)
	return err
}
