// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	UserID        string
	PostID        int32
	Title         string
	Content       string
	LikesCount    int32
	DislikesCount int32
	CommentsCount int32
	ViewsCount    int32
}

type User struct {
	UserID         string
	Username       string
	Password       pgtype.Text
	FollowersCount int32
	FollowingCount int32
	ViewsCount     int32
	LikesCount     int32
}
