// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatRoom struct {
	ID        int64
	User1ID   int64
	User2ID   int64
	CreatedAt pgtype.Timestamp
}

type Comment struct {
	ID        int64
	PostID    int64
	UserID    int64
	Content   string
	CreatedAt pgtype.Timestamp
}

type Follow struct {
	FollowerID  int64
	FollowingID int64
	CreatedAt   pgtype.Timestamp
}

type Post struct {
	ID            int64
	UserID        int64
	Title         string
	Description   string
	Url           pgtype.Text
	CommentsCount pgtype.Int4
	LikesCount    pgtype.Int4
	HatesCount    pgtype.Int4
	SharesCount   pgtype.Int4
	SavesCount    pgtype.Int4
	Point         pgtype.Int4
	CreatedAt     pgtype.Timestamp
}

type PostReaction struct {
	PostID       int64
	UserID       int64
	ReactionType string
	CreatedAt    pgtype.Timestamp
}

type PrivateMessage struct {
	ID          int64
	RoomID      int64
	SenderID    int64
	MessageText string
	IsRead      pgtype.Bool
	CreatedAt   pgtype.Timestamp
}

type User struct {
	ID          int64
	Username    string
	Password    string
	Email       pgtype.Text
	Name        string
	Description pgtype.Text
	Followers   pgtype.Int4
	Following   pgtype.Int4
	Views       pgtype.Int4
	LikesCount  pgtype.Int4
	Point       pgtype.Int4
	PostsCount  pgtype.Int4
	City        pgtype.Text
	Location    pgtype.Text
	BirthDate   pgtype.Date
	CreatedAt   pgtype.Timestamp
}
