// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const auditPostActualCounters = `-- name: AuditPostActualCounters :one

SELECT 
    p.id AS post_id,
    p.likes_count AS cached_likes,
    p.hates_count AS cached_hates,
    p.comments_count AS cached_comments,
    (SELECT COUNT(*)::int FROM post_reactions WHERE post_id = p.id AND reaction_type = 'LIKE') AS actual_likes,
    (SELECT COUNT(*)::int FROM post_reactions WHERE post_id = p.id AND reaction_type = 'HATE') AS actual_hates,
    (SELECT COUNT(*)::int FROM comments WHERE post_id = p.id) AS actual_comments
FROM posts p
WHERE p.id = $1
`

type AuditPostActualCountersRow struct {
	PostID         int64
	CachedLikes    pgtype.Int4
	CachedHates    pgtype.Int4
	CachedComments pgtype.Int4
	ActualLikes    int32
	ActualHates    int32
	ActualComments int32
}

// ====================================================================================
// 6. استعلامات مراجعة وتدقيق ومزامنة العدادات (Counters Audit & Integrity Sync)
// ====================================================================================
// كويري فحص النزاهة (Integrity Audit): يقوم بحساب الأعداد الحقيقية (اللايكات والتعليقات والـ Hates)
// مباشرة من جداول التفاعلات الأساسية لمقارنتها مع العدادات المخزنة في جدول الـ posts في حال حدوث Desync.
func (q *Queries) AuditPostActualCounters(ctx context.Context, id int64) (AuditPostActualCountersRow, error) {
	row := q.db.QueryRow(ctx, auditPostActualCounters, id)
	var i AuditPostActualCountersRow
	err := row.Scan(
		&i.PostID,
		&i.CachedLikes,
		&i.CachedHates,
		&i.CachedComments,
		&i.ActualLikes,
		&i.ActualHates,
		&i.ActualComments,
	)
	return i, err
}

const batchGetPostsByIDs = `-- name: BatchGetPostsByIDs :many



SELECT 
    p.id AS post_id, p.title, p.description, p.url, 
    p.comments_count, p.likes_count, p.hates_count, p.shares_count, p.saves_count, p.point, p.created_at,
    u.id AS author_id, u.username AS author_username, u.name AS author_name
FROM posts p
INNER JOIN users u ON p.user_id = u.id
WHERE p.id = ANY($1::bigint[])
ORDER BY ARRAY_POSITION($1::bigint[], p.id)
`

type BatchGetPostsByIDsRow struct {
	PostID         int64
	Title          string
	Description    string
	Url            pgtype.Text
	CommentsCount  pgtype.Int4
	LikesCount     pgtype.Int4
	HatesCount     pgtype.Int4
	SharesCount    pgtype.Int4
	SavesCount     pgtype.Int4
	Point          pgtype.Int4
	CreatedAt      pgtype.Timestamp
	AuthorID       int64
	AuthorUsername string
	AuthorName     string
}

// تم التعديل هنا صراحة لمنع الـ Ambiguity
// ====================================================================================
// 7. العمليات الجماعية عالية الأداء والتحليلات (Batch API Operations & Analytics)
// ====================================================================================
// جلب مصفوفة كاملة من المنشورات بطلب واحد (Single Round-Trip)
// يُستخدم عند جلب قائمة المفضلة المحفوظة للمستخدم، أو المنشورات المرتبطة بالإشعارات المستلمة.
func (q *Queries) BatchGetPostsByIDs(ctx context.Context, dollar_1 []int64) ([]BatchGetPostsByIDsRow, error) {
	rows, err := q.db.Query(ctx, batchGetPostsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchGetPostsByIDsRow
	for rows.Next() {
		var i BatchGetPostsByIDsRow
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.CommentsCount,
			&i.LikesCount,
			&i.HatesCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.Point,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPost = `-- name: CreatePost :one

INSERT INTO posts (
    user_id,
    title,
    description,
    url
) VALUES (
    $1,
    TRIM($2),
    TRIM($3),
    NULLIF(TRIM($4), '') -- حماية: تحويل الروابط الفارغة إلى NULL تلقائياً
)
RETURNING id, user_id, title, description, url, comments_count, likes_count, hates_count, shares_count, saves_count, point, created_at
`

type CreatePostParams struct {
	UserID  int64
	Btrim   string
	Btrim_2 string
	Btrim_3 string
}

// ====================================================================================
// 1. العمليات الأساسية وإدارة المنشورات بوضع الحماية الصارم (Secure Post CRUD Engine)
// ====================================================================================
// إنشاء منشور جديد وتصفير العدادات تلقائياً مع إرجاع كامل بيانات الصف لحقنها في الواجهة فوراً
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.UserID,
		arg.Btrim,
		arg.Btrim_2,
		arg.Btrim_3,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.CommentsCount,
		&i.LikesCount,
		&i.HatesCount,
		&i.SharesCount,
		&i.SavesCount,
		&i.Point,
		&i.CreatedAt,
	)
	return i, err
}

const decrementPostComments = `-- name: DecrementPostComments :exec
UPDATE posts SET comments_count = GREATEST(0, comments_count - 1) WHERE id = $1
`

func (q *Queries) DecrementPostComments(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementPostComments, id)
	return err
}

const decrementPostHatesCount = `-- name: DecrementPostHatesCount :exec
UPDATE posts SET hates_count = GREATEST(0, hates_count - 1) WHERE id = $1
`

func (q *Queries) DecrementPostHatesCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementPostHatesCount, id)
	return err
}

const decrementPostLikesCount = `-- name: DecrementPostLikesCount :exec
UPDATE posts SET likes_count = GREATEST(0, likes_count - 1) WHERE id = $1
`

func (q *Queries) DecrementPostLikesCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementPostLikesCount, id)
	return err
}

const decrementPostSaves = `-- name: DecrementPostSaves :exec
UPDATE posts SET saves_count = GREATEST(0, saves_count - 1) WHERE id = $1
`

func (q *Queries) DecrementPostSaves(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementPostSaves, id)
	return err
}

const deletePostSecure = `-- name: DeletePostSecure :exec
DELETE FROM posts
WHERE id = $1 AND user_id = $2
`

type DeletePostSecureParams struct {
	ID     int64
	UserID int64
}

// ميزة حذف المنشور نهائياً: قيد أمان صارم يمنع أي مستخدم من تزوير الطلبات وحذف منشورات غيره
func (q *Queries) DeletePostSecure(ctx context.Context, arg DeletePostSecureParams) error {
	_, err := q.db.Exec(ctx, deletePostSecure, arg.ID, arg.UserID)
	return err
}

const getPlatformGlobalPostStats = `-- name: GetPlatformGlobalPostStats :one
SELECT 
    COUNT(*)::bigint AS total_posts_created,
    COALESCE(SUM(likes_count), 0)::bigint AS total_platform_likes,
    COALESCE(SUM(comments_count), 0)::bigint AS total_platform_comments,
    COALESCE(AVG(point), 0.0)::float AS average_posts_points
FROM posts
`

type GetPlatformGlobalPostStatsRow struct {
	TotalPostsCreated     int64
	TotalPlatformLikes    int64
	TotalPlatformComments int64
	AveragePostsPoints    float64
}

// لوحة تحليلات المنصة (Admin Global Analytics Dashboard):
// يعطيك إحصائيات عامة عن المنشورات (إجمالي عدد المنشورات، مجموع اللايكات، متوسط نقاط المنشورات) لمراقبة نشاط التطبيق.
func (q *Queries) GetPlatformGlobalPostStats(ctx context.Context) (GetPlatformGlobalPostStatsRow, error) {
	row := q.db.QueryRow(ctx, getPlatformGlobalPostStats)
	var i GetPlatformGlobalPostStatsRow
	err := row.Scan(
		&i.TotalPostsCreated,
		&i.TotalPlatformLikes,
		&i.TotalPlatformComments,
		&i.AveragePostsPoints,
	)
	return i, err
}

const getPostDetailedByID = `-- name: GetPostDetailedByID :one
SELECT 
    p.id AS post_id, p.title, p.description, p.url, 
    p.comments_count, p.likes_count, p.hates_count, p.shares_count, p.saves_count, p.point, p.created_at AS post_created_at,
    u.id AS author_id, u.username AS author_username, u.name AS author_name
FROM posts p
INNER JOIN users u ON p.user_id = u.id
WHERE p.id = $1
LIMIT 1
`

type GetPostDetailedByIDRow struct {
	PostID         int64
	Title          string
	Description    string
	Url            pgtype.Text
	CommentsCount  pgtype.Int4
	LikesCount     pgtype.Int4
	HatesCount     pgtype.Int4
	SharesCount    pgtype.Int4
	SavesCount     pgtype.Int4
	Point          pgtype.Int4
	PostCreatedAt  pgtype.Timestamp
	AuthorID       int64
	AuthorUsername string
	AuthorName     string
}

// جلب تفاصيل منشور محدد مدمجاً (JOIN) مع بيانات كاتبه (الاسم، اليوزر) بطلب واحد فائق السرعة
func (q *Queries) GetPostDetailedByID(ctx context.Context, id int64) (GetPostDetailedByIDRow, error) {
	row := q.db.QueryRow(ctx, getPostDetailedByID, id)
	var i GetPostDetailedByIDRow
	err := row.Scan(
		&i.PostID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.CommentsCount,
		&i.LikesCount,
		&i.HatesCount,
		&i.SharesCount,
		&i.SavesCount,
		&i.Point,
		&i.PostCreatedAt,
		&i.AuthorID,
		&i.AuthorUsername,
		&i.AuthorName,
	)
	return i, err
}

const getPostDetailedWithViewerContext = `-- name: GetPostDetailedWithViewerContext :one
SELECT 
    p.id AS post_id, p.title, p.description, p.url, 
    p.comments_count, p.likes_count, p.hates_count, p.shares_count, p.saves_count, p.point, p.created_at AS post_created_at,
    u.id AS author_id, u.username AS author_username, u.name AS author_name,
    COALESCE((SELECT pr.reaction_type FROM post_reactions pr WHERE pr.post_id = p.id AND pr.user_id = $2), '') AS viewer_reaction
FROM posts p
INNER JOIN users u ON p.user_id = u.id
WHERE p.id = $1
LIMIT 1
`

type GetPostDetailedWithViewerContextParams struct {
	ID     int64
	UserID int64
}

type GetPostDetailedWithViewerContextRow struct {
	PostID         int64
	Title          string
	Description    string
	Url            pgtype.Text
	CommentsCount  pgtype.Int4
	LikesCount     pgtype.Int4
	HatesCount     pgtype.Int4
	SharesCount    pgtype.Int4
	SavesCount     pgtype.Int4
	Point          pgtype.Int4
	PostCreatedAt  pgtype.Timestamp
	AuthorID       int64
	AuthorUsername string
	AuthorName     string
	ViewerReaction interface{}
}

// كويري التفاصيل الذهبي (Single Post View): يجلب بيانات المنشور والكاتب، وبنفس الوقت يتحقق
// مما إذا كان المستخدم الحالي الممرر معرفه ($2) قد قام بعمل (LIKE) أو (HATE) لهذا المنشور أم لا!
// (مهم جداً لإضاءة أزرار التفاعل باللون الأزرق أو الأحمر فور فتح المنشور)
func (q *Queries) GetPostDetailedWithViewerContext(ctx context.Context, arg GetPostDetailedWithViewerContextParams) (GetPostDetailedWithViewerContextRow, error) {
	row := q.db.QueryRow(ctx, getPostDetailedWithViewerContext, arg.ID, arg.UserID)
	var i GetPostDetailedWithViewerContextRow
	err := row.Scan(
		&i.PostID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.CommentsCount,
		&i.LikesCount,
		&i.HatesCount,
		&i.SharesCount,
		&i.SavesCount,
		&i.Point,
		&i.PostCreatedAt,
		&i.AuthorID,
		&i.AuthorUsername,
		&i.AuthorName,
		&i.ViewerReaction,
	)
	return i, err
}

const incrementPostComments = `-- name: IncrementPostComments :exec
UPDATE posts SET comments_count = comments_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostComments(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementPostComments, id)
	return err
}

const incrementPostHatesCount = `-- name: IncrementPostHatesCount :exec
UPDATE posts SET hates_count = hates_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostHatesCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementPostHatesCount, id)
	return err
}

const incrementPostLikesCount = `-- name: IncrementPostLikesCount :exec
UPDATE posts SET likes_count = likes_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostLikesCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementPostLikesCount, id)
	return err
}

const incrementPostSaves = `-- name: IncrementPostSaves :exec
UPDATE posts SET saves_count = saves_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostSaves(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementPostSaves, id)
	return err
}

const incrementPostShares = `-- name: IncrementPostShares :exec
UPDATE posts SET shares_count = shares_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostShares(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementPostShares, id)
	return err
}

const listGlobalRecentFeedWithCursor = `-- name: ListGlobalRecentFeedWithCursor :many
SELECT 
    p.id AS post_id, p.title, p.description, p.url, 
    p.comments_count, p.likes_count, p.hates_count, p.shares_count, p.saves_count, p.point, p.created_at AS post_created_at,
    u.id AS author_id, u.username AS author_username, u.name AS author_name,
    COALESCE((SELECT pr.reaction_type FROM post_reactions pr WHERE pr.post_id = p.id AND pr.user_id = $1), '') AS viewer_reaction
FROM posts p
INNER JOIN users u ON p.user_id = u.id
WHERE ($2::bigint = 0 OR p.id < $2)
ORDER BY p.id DESC
LIMIT $3
`

type ListGlobalRecentFeedWithCursorParams struct {
	UserID  int64
	Column2 int64
	Limit   int32
}

type ListGlobalRecentFeedWithCursorRow struct {
	PostID         int64
	Title          string
	Description    string
	Url            pgtype.Text
	CommentsCount  pgtype.Int4
	LikesCount     pgtype.Int4
	HatesCount     pgtype.Int4
	SharesCount    pgtype.Int4
	SavesCount     pgtype.Int4
	Point          pgtype.Int4
	PostCreatedAt  pgtype.Timestamp
	AuthorID       int64
	AuthorUsername string
	AuthorName     string
	ViewerReaction interface{}
}

// خلاصة أحدث المنشورات العامة (Global / Explore Recent Feed): يجلب أحدث المنشورات على مستوى المنصة بأكملها
// مع دمج سياق المشاهد الحالي ($1) لمعرفة تفاعلاته ودعم التمرير اللانهائي (Cursor).
func (q *Queries) ListGlobalRecentFeedWithCursor(ctx context.Context, arg ListGlobalRecentFeedWithCursorParams) ([]ListGlobalRecentFeedWithCursorRow, error) {
	rows, err := q.db.Query(ctx, listGlobalRecentFeedWithCursor, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGlobalRecentFeedWithCursorRow
	for rows.Next() {
		var i ListGlobalRecentFeedWithCursorRow
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.CommentsCount,
			&i.LikesCount,
			&i.HatesCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.Point,
			&i.PostCreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorName,
			&i.ViewerReaction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMostDiscussedPostsFeed = `-- name: ListMostDiscussedPostsFeed :many
SELECT 
    p.id AS post_id, p.title, p.description, p.url, 
    p.comments_count, p.likes_count, p.point, p.created_at,
    u.username AS author_username, u.name AS author_name
FROM posts p
INNER JOIN users u ON p.user_id = u.id
ORDER BY p.comments_count DESC, p.id DESC
LIMIT $1 OFFSET $2
`

type ListMostDiscussedPostsFeedParams struct {
	Limit  int32
	Offset int32
}

type ListMostDiscussedPostsFeedRow struct {
	PostID         int64
	Title          string
	Description    string
	Url            pgtype.Text
	CommentsCount  pgtype.Int4
	LikesCount     pgtype.Int4
	Point          pgtype.Int4
	CreatedAt      pgtype.Timestamp
	AuthorUsername string
	AuthorName     string
}

// خلاصة النقاشات الساخنة (Most Discussed Feed): ترتيب المنشورات حسب أكثرها استقبالاً للتعليقات (comments_count)
func (q *Queries) ListMostDiscussedPostsFeed(ctx context.Context, arg ListMostDiscussedPostsFeedParams) ([]ListMostDiscussedPostsFeedRow, error) {
	rows, err := q.db.Query(ctx, listMostDiscussedPostsFeed, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMostDiscussedPostsFeedRow
	for rows.Next() {
		var i ListMostDiscussedPostsFeedRow
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.CommentsCount,
			&i.LikesCount,
			&i.Point,
			&i.CreatedAt,
			&i.AuthorUsername,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalizedHomeFeedWithViewerContext = `-- name: ListPersonalizedHomeFeedWithViewerContext :many

SELECT 
    p.id AS post_id, p.title, p.description, p.url, 
    p.comments_count, p.likes_count, p.hates_count, p.shares_count, p.saves_count, p.point, p.created_at AS post_created_at,
    u.id AS author_id, u.username AS author_username, u.name AS author_name,
    COALESCE((SELECT pr.reaction_type FROM post_reactions pr WHERE pr.post_id = p.id AND pr.user_id = $1), '') AS viewer_reaction
FROM posts p
INNER JOIN users u ON p.user_id = u.id
WHERE p.user_id IN (SELECT following_id FROM follows WHERE follower_id = $1)
  AND ($2::bigint = 0 OR p.id < $2)
ORDER BY p.id DESC
LIMIT $3
`

type ListPersonalizedHomeFeedWithViewerContextParams struct {
	UserID  int64
	Column2 int64
	Limit   int32
}

type ListPersonalizedHomeFeedWithViewerContextRow struct {
	PostID         int64
	Title          string
	Description    string
	Url            pgtype.Text
	CommentsCount  pgtype.Int4
	LikesCount     pgtype.Int4
	HatesCount     pgtype.Int4
	SharesCount    pgtype.Int4
	SavesCount     pgtype.Int4
	Point          pgtype.Int4
	PostCreatedAt  pgtype.Timestamp
	AuthorID       int64
	AuthorUsername string
	AuthorName     string
	ViewerReaction interface{}
}

// ====================================================================================
// 2. محركات الخلاصات اللانهائية الذكية (Advanced Feed Engines - Contextual Cursor Pagination)
// ====================================================================================
// كويري الصفحة الرئيسية الأقوى (Timeline Feed):
// 1. يجلب منشورات الأشخاص الذين يتابعهم المستخدم ($1) فقط.
// 2. يدعم الـ Cursor Pagination لضمان الانسيابية والسرعة (p.id < $2).
// 3. يحقن حالة تفاعل المستخدم الحالي ($1) مع كل منشور (viewer_reaction) لترسم الأزرار متفاعلة وجاهزة في الـ List View!
func (q *Queries) ListPersonalizedHomeFeedWithViewerContext(ctx context.Context, arg ListPersonalizedHomeFeedWithViewerContextParams) ([]ListPersonalizedHomeFeedWithViewerContextRow, error) {
	rows, err := q.db.Query(ctx, listPersonalizedHomeFeedWithViewerContext, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonalizedHomeFeedWithViewerContextRow
	for rows.Next() {
		var i ListPersonalizedHomeFeedWithViewerContextRow
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.CommentsCount,
			&i.LikesCount,
			&i.HatesCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.Point,
			&i.PostCreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorName,
			&i.ViewerReaction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsCommentedOnByUser = `-- name: ListPostsCommentedOnByUser :many
SELECT DISTINCT ON (p.id)
    p.id AS post_id, p.title, p.description, p.created_at,
    u.username AS author_username
FROM comments c
INNER JOIN posts p ON c.post_id = p.id
INNER JOIN users u ON p.user_id = u.id
WHERE c.user_id = $1
ORDER BY p.id DESC
LIMIT $2 OFFSET $3
`

type ListPostsCommentedOnByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

type ListPostsCommentedOnByUserRow struct {
	PostID         int64
	Title          string
	Description    string
	CreatedAt      pgtype.Timestamp
	AuthorUsername string
}

// جلب المنشورات الفريدة (DISTINCT) التي قام المستخدم ($1) بترك تعليق عليها مسبقاً (سجل النشاط النصي)
func (q *Queries) ListPostsCommentedOnByUser(ctx context.Context, arg ListPostsCommentedOnByUserParams) ([]ListPostsCommentedOnByUserRow, error) {
	rows, err := q.db.Query(ctx, listPostsCommentedOnByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsCommentedOnByUserRow
	for rows.Next() {
		var i ListPostsCommentedOnByUserRow
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsHatedByUserWithCursor = `-- name: ListPostsHatedByUserWithCursor :many
SELECT 
    p.id AS post_id, p.title, p.description, p.url, 
    p.comments_count, p.hates_count, p.point, p.created_at,
    u.username AS author_username, u.name AS author_name
FROM post_reactions pr
INNER JOIN posts p ON pr.post_id = p.id
INNER JOIN users u ON p.user_id = u.id
WHERE pr.user_id = $1 AND pr.reaction_type = 'HATE'
  AND ($2::bigint = 0 OR p.id < $2)
ORDER BY pr.created_at DESC
LIMIT $3
`

type ListPostsHatedByUserWithCursorParams struct {
	UserID  int64
	Column2 int64
	Limit   int32
}

type ListPostsHatedByUserWithCursorRow struct {
	PostID         int64
	Title          string
	Description    string
	Url            pgtype.Text
	CommentsCount  pgtype.Int4
	HatesCount     pgtype.Int4
	Point          pgtype.Int4
	CreatedAt      pgtype.Timestamp
	AuthorUsername string
	AuthorName     string
}

// شاشة "المنشورات التي لم تعجبني": جلب كافة المنشورات التي تفاعل معها مستخدم معين ($1) بـ HATE
func (q *Queries) ListPostsHatedByUserWithCursor(ctx context.Context, arg ListPostsHatedByUserWithCursorParams) ([]ListPostsHatedByUserWithCursorRow, error) {
	rows, err := q.db.Query(ctx, listPostsHatedByUserWithCursor, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsHatedByUserWithCursorRow
	for rows.Next() {
		var i ListPostsHatedByUserWithCursorRow
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.CommentsCount,
			&i.HatesCount,
			&i.Point,
			&i.CreatedAt,
			&i.AuthorUsername,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsLikedByUserWithCursor = `-- name: ListPostsLikedByUserWithCursor :many

SELECT 
    p.id AS post_id, p.title, p.description, p.url, 
    p.comments_count, p.likes_count, p.point, p.created_at,
    u.username AS author_username, u.name AS author_name
FROM post_reactions pr
INNER JOIN posts p ON pr.post_id = p.id
INNER JOIN users u ON p.user_id = u.id
WHERE pr.user_id = $1 AND pr.reaction_type = 'LIKE'
  AND ($2::bigint = 0 OR p.id < $2)
ORDER BY pr.created_at DESC
LIMIT $3
`

type ListPostsLikedByUserWithCursorParams struct {
	UserID  int64
	Column2 int64
	Limit   int32
}

type ListPostsLikedByUserWithCursorRow struct {
	PostID         int64
	Title          string
	Description    string
	Url            pgtype.Text
	CommentsCount  pgtype.Int4
	LikesCount     pgtype.Int4
	Point          pgtype.Int4
	CreatedAt      pgtype.Timestamp
	AuthorUsername string
	AuthorName     string
}

// ====================================================================================
// 3. سجلات تفاعلات المستخدم التاريخية للمنشورات (User Post Interaction History)
// ====================================================================================
// شاشة "المنشورات التي أعجبتني": جلب كافة المنشورات التي قام مستخدم معين ($1) بالإعجاب بها عبر جدول التفاعلات
func (q *Queries) ListPostsLikedByUserWithCursor(ctx context.Context, arg ListPostsLikedByUserWithCursorParams) ([]ListPostsLikedByUserWithCursorRow, error) {
	rows, err := q.db.Query(ctx, listPostsLikedByUserWithCursor, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsLikedByUserWithCursorRow
	for rows.Next() {
		var i ListPostsLikedByUserWithCursorRow
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.CommentsCount,
			&i.LikesCount,
			&i.Point,
			&i.CreatedAt,
			&i.AuthorUsername,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrendingPostsFeed = `-- name: ListTrendingPostsFeed :many
SELECT 
    p.id AS post_id, p.title, p.description, p.url, 
    p.comments_count, p.likes_count, p.hates_count, p.shares_count, p.saves_count, p.point, p.created_at,
    u.id AS author_id, u.username AS author_username, u.name AS author_name
FROM posts p
INNER JOIN users u ON p.user_id = u.id
ORDER BY p.point DESC, p.id DESC
LIMIT $1 OFFSET $2
`

type ListTrendingPostsFeedParams struct {
	Limit  int32
	Offset int32
}

type ListTrendingPostsFeedRow struct {
	PostID         int64
	Title          string
	Description    string
	Url            pgtype.Text
	CommentsCount  pgtype.Int4
	LikesCount     pgtype.Int4
	HatesCount     pgtype.Int4
	SharesCount    pgtype.Int4
	SavesCount     pgtype.Int4
	Point          pgtype.Int4
	CreatedAt      pgtype.Timestamp
	AuthorID       int64
	AuthorUsername string
	AuthorName     string
}

// قسم المنشورات الشائعة (Trending Feed): ترتيب عالمي للمنشورات الأكثر تفاعلاً وشهرة بناءً على حقل النقاط (point) الأعلى
func (q *Queries) ListTrendingPostsFeed(ctx context.Context, arg ListTrendingPostsFeedParams) ([]ListTrendingPostsFeedRow, error) {
	rows, err := q.db.Query(ctx, listTrendingPostsFeed, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrendingPostsFeedRow
	for rows.Next() {
		var i ListTrendingPostsFeedRow
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.CommentsCount,
			&i.LikesCount,
			&i.HatesCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.Point,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProfilePostsWithCursor = `-- name: ListUserProfilePostsWithCursor :many
SELECT 
    p.id AS post_id, p.title, p.description, p.url, 
    p.comments_count, p.likes_count, p.point, p.created_at
FROM posts p
WHERE p.user_id = $1
  AND ($2::bigint = 0 OR p.id < $2)
ORDER BY p.id DESC
LIMIT $3
`

type ListUserProfilePostsWithCursorParams struct {
	UserID  int64
	Column2 int64
	Limit   int32
}

type ListUserProfilePostsWithCursorRow struct {
	PostID        int64
	Title         string
	Description   string
	Url           pgtype.Text
	CommentsCount pgtype.Int4
	LikesCount    pgtype.Int4
	Point         pgtype.Int4
	CreatedAt     pgtype.Timestamp
}

// شاشة الملف الشخصي (Profile Feed): جلب منشورات مستخدم معين ($1) مع الترتيب التنازلي والـ Cursor Pagination
func (q *Queries) ListUserProfilePostsWithCursor(ctx context.Context, arg ListUserProfilePostsWithCursorParams) ([]ListUserProfilePostsWithCursorRow, error) {
	rows, err := q.db.Query(ctx, listUserProfilePostsWithCursor, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserProfilePostsWithCursorRow
	for rows.Next() {
		var i ListUserProfilePostsWithCursorRow
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.CommentsCount,
			&i.LikesCount,
			&i.Point,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostsAdvanced = `-- name: SearchPostsAdvanced :many

SELECT 
    p.id AS post_id, p.title, p.description, p.url, 
    p.comments_count, p.likes_count, p.hates_count, p.shares_count, p.saves_count, p.point, p.created_at,
    u.username AS author_username, u.name AS author_name
FROM posts p
INNER JOIN users u ON p.user_id = u.id
WHERE ($1::text = '' OR p.title ILIKE '%' || $1 || '%' OR p.description ILIKE '%' || $1 || '%')
  AND ($2::bigint = 0 OR p.user_id = $2)
  AND (p.point >= $3::int)
ORDER BY p.id DESC
LIMIT $4 OFFSET $5
`

type SearchPostsAdvancedParams struct {
	Column1 string
	Column2 int64
	Column3 int32
	Limit   int32
	Offset  int32
}

type SearchPostsAdvancedRow struct {
	PostID         int64
	Title          string
	Description    string
	Url            pgtype.Text
	CommentsCount  pgtype.Int4
	LikesCount     pgtype.Int4
	HatesCount     pgtype.Int4
	SharesCount    pgtype.Int4
	SavesCount     pgtype.Int4
	Point          pgtype.Int4
	CreatedAt      pgtype.Timestamp
	AuthorUsername string
	AuthorName     string
}

// ====================================================================================
// 4. محرك البحث المتقدم والفلترة (Dynamic Criteria Search Engine)
// ====================================================================================
// كويري البحث الذكي والشامل للمنصة: يبحث بالنص الجزئي (Fuzzy) في (العنوان والوصف)،
// ويقبل الفلترة الاختيارية لحساب مستخدم معين، ويشترط حداً أدنى من النقاط، مع دعم كامل للـ Pagination السريع.
func (q *Queries) SearchPostsAdvanced(ctx context.Context, arg SearchPostsAdvancedParams) ([]SearchPostsAdvancedRow, error) {
	rows, err := q.db.Query(ctx, searchPostsAdvanced,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsAdvancedRow
	for rows.Next() {
		var i SearchPostsAdvancedRow
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.CommentsCount,
			&i.LikesCount,
			&i.HatesCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.Point,
			&i.CreatedAt,
			&i.AuthorUsername,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const synchronizePostCounters = `-- name: SynchronizePostCounters :exec
UPDATE posts
SET 
    likes_count = (SELECT COUNT(*)::int FROM post_reactions WHERE post_id = posts.id AND reaction_type = 'LIKE'),
    hates_count = (SELECT COUNT(*)::int FROM post_reactions WHERE post_id = posts.id AND reaction_type = 'HATE'),
    comments_count = (SELECT COUNT(*)::int FROM comments WHERE post_id = posts.id)
WHERE posts.id = $1
`

// كويري الإصلاح والمزامنة الذاتية (Self-Healing Query)
func (q *Queries) SynchronizePostCounters(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, synchronizePostCounters, id)
	return err
}

const updatePostPoints = `-- name: UpdatePostPoints :exec

UPDATE posts SET point = point + $2 WHERE id = $1
`

type UpdatePostPointsParams struct {
	ID    int64
	Point pgtype.Int4
}

// ====================================================================================
// 5. إدارة العدادات الذرية وحماية نقاط النظام (Safe Atomic Counters Operations)
// ====================================================================================
// نظام احتساب خوارزمية المنشور: زيادة نقاط المنشور أو إنقاصها برمجياً (عند حدوث لايك، تعليق، أو شير)
func (q *Queries) UpdatePostPoints(ctx context.Context, arg UpdatePostPointsParams) error {
	_, err := q.db.Exec(ctx, updatePostPoints, arg.ID, arg.Point)
	return err
}

const updatePostSecure = `-- name: UpdatePostSecure :one
UPDATE posts
SET
    title = TRIM($3),
    description = TRIM($4),
    url = NULLIF(TRIM($5), '')
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, url, created_at
`

type UpdatePostSecureParams struct {
	ID      int64
	UserID  int64
	Btrim   string
	Btrim_2 string
	Btrim_3 string
}

type UpdatePostSecureRow struct {
	ID          int64
	UserID      int64
	Title       string
	Description string
	Url         pgtype.Text
	CreatedAt   pgtype.Timestamp
}

// ميزة تعديل المنشور (Edit Post): قيد أمان صارم يمنع التعديل إلا إذا كان المستخدم الحالي ($2) هو الكاتب الفعلي
func (q *Queries) UpdatePostSecure(ctx context.Context, arg UpdatePostSecureParams) (UpdatePostSecureRow, error) {
	row := q.db.QueryRow(ctx, updatePostSecure,
		arg.ID,
		arg.UserID,
		arg.Btrim,
		arg.Btrim_2,
		arg.Btrim_3,
	)
	var i UpdatePostSecureRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}
