// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id, post_id, title, content)
VALUES ($1, $2, $3, $4)
RETURNING user_id, post_id, title, content, likes_count, dislikes_count, comments_count, views_count
`

type CreatePostParams struct {
	UserID  string
	PostID  int32
	Title   string
	Content string
}

// إنشاء منشور جديد
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.UserID,
		arg.PostID,
		arg.Title,
		arg.Content,
	)
	var i Post
	err := row.Scan(
		&i.UserID,
		&i.PostID,
		&i.Title,
		&i.Content,
		&i.LikesCount,
		&i.DislikesCount,
		&i.CommentsCount,
		&i.ViewsCount,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (user_id, username, password)
VALUES ($1, $2, $3)
RETURNING user_id, username, password, followers_count, following_count, views_count, likes_count
`

type CreateUserParams struct {
	UserID   string
	Username string
	Password pgtype.Text
}

// ========================================================
// 1. استعلامات جدول المستخدمين (Users Management)
// ========================================================
// إنشاء مستخدم جديد
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.UserID, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.ViewsCount,
		&i.LikesCount,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE user_id = $1 AND post_id = $2
`

type DeletePostParams struct {
	UserID string
	PostID int32
}

// 💡 تم تصحيح الخطأ هنا بإزالة الـ p الزائدة تماماً
func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.Exec(ctx, deletePost, arg.UserID, arg.PostID)
	return err
}

const followUser = `-- name: FollowUser :exec
UPDATE users
SET following_count = following_count + 1 WHERE user_id = $1
`

func (q *Queries) FollowUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, followUser, userID)
	return err
}

const getNextPostId = `-- name: GetNextPostId :one

SELECT COALESCE(MAX(post_id), 0) + 1 AS next_post_id
FROM posts
WHERE user_id = $1
`

// ========================================================
// 2. استعلامات جدول المنشورات (Posts Management)
// ========================================================
// يحسب لك الـ post_id القادم لهذا المستخدم تلقائياً
func (q *Queries) GetNextPostId(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, getNextPostId, userID)
	var next_post_id int32
	err := row.Scan(&next_post_id)
	return next_post_id, err
}

const getPostWithAuthor = `-- name: GetPostWithAuthor :one
SELECT 
    p.user_id, p.post_id, p.title, p.content, 
    p.likes_count, p.dislikes_count, p.comments_count, p.views_count,
    u.username AS author_username
FROM posts AS p
JOIN users AS u ON p.user_id = u.user_id
WHERE p.user_id = $1 AND p.post_id = $2 LIMIT 1
`

type GetPostWithAuthorParams struct {
	UserID string
	PostID int32
}

type GetPostWithAuthorRow struct {
	UserID         string
	PostID         int32
	Title          string
	Content        string
	LikesCount     int32
	DislikesCount  int32
	CommentsCount  int32
	ViewsCount     int32
	AuthorUsername string
}

// يجلب لك البوست مع الـ username حق الكاتب
func (q *Queries) GetPostWithAuthor(ctx context.Context, arg GetPostWithAuthorParams) (GetPostWithAuthorRow, error) {
	row := q.db.QueryRow(ctx, getPostWithAuthor, arg.UserID, arg.PostID)
	var i GetPostWithAuthorRow
	err := row.Scan(
		&i.UserID,
		&i.PostID,
		&i.Title,
		&i.Content,
		&i.LikesCount,
		&i.DislikesCount,
		&i.CommentsCount,
		&i.ViewsCount,
		&i.AuthorUsername,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT user_id, username, password, followers_count, following_count, views_count, likes_count
FROM users
WHERE user_id = $1 LIMIT 1
`

// جلب بيانات مستخدم محدد بالـ ID
func (q *Queries) GetUserById(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.ViewsCount,
		&i.LikesCount,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, username, password, followers_count, following_count, views_count, likes_count
FROM users
WHERE username = $1 LIMIT 1
`

// جلب بيانات مستخدم عن طريق اسم المستخدم (مفيد في تسجيل الدخول)
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.ViewsCount,
		&i.LikesCount,
	)
	return i, err
}

const incrementPostCommentCount = `-- name: IncrementPostCommentCount :exec
UPDATE posts
SET comments_count = comments_count + 1
WHERE user_id = $1 AND post_id = $2
`

type IncrementPostCommentCountParams struct {
	UserID string
	PostID int32
}

func (q *Queries) IncrementPostCommentCount(ctx context.Context, arg IncrementPostCommentCountParams) error {
	_, err := q.db.Exec(ctx, incrementPostCommentCount, arg.UserID, arg.PostID)
	return err
}

const incrementPostDislike = `-- name: IncrementPostDislike :exec
UPDATE posts
SET dislikes_count = dislikes_count + 1
WHERE user_id = $1 AND post_id = $2
`

type IncrementPostDislikeParams struct {
	UserID string
	PostID int32
}

func (q *Queries) IncrementPostDislike(ctx context.Context, arg IncrementPostDislikeParams) error {
	_, err := q.db.Exec(ctx, incrementPostDislike, arg.UserID, arg.PostID)
	return err
}

const incrementPostLike = `-- name: IncrementPostLike :exec
UPDATE posts
SET likes_count = likes_count + 1
WHERE user_id = $1 AND post_id = $2
`

type IncrementPostLikeParams struct {
	UserID string
	PostID int32
}

func (q *Queries) IncrementPostLike(ctx context.Context, arg IncrementPostLikeParams) error {
	_, err := q.db.Exec(ctx, incrementPostLike, arg.UserID, arg.PostID)
	return err
}

const incrementPostView = `-- name: IncrementPostView :exec

UPDATE posts
SET views_count = views_count + 1
WHERE user_id = $1 AND post_id = $2
`

type IncrementPostViewParams struct {
	UserID string
	PostID int32
}

// ========================================================
// 4. عدادات التفاعل الذكية (Engagement & Counters)
// ========================================================
func (q *Queries) IncrementPostView(ctx context.Context, arg IncrementPostViewParams) error {
	_, err := q.db.Exec(ctx, incrementPostView, arg.UserID, arg.PostID)
	return err
}

const listGlobalFeed = `-- name: ListGlobalFeed :many

SELECT 
    p.user_id, p.post_id, p.title, p.content, 
    p.likes_count, p.dislikes_count, p.comments_count, p.views_count,
    u.username AS author_username
FROM posts AS p
JOIN users AS u ON p.user_id = u.user_id
ORDER BY p.views_count DESC, p.post_id DESC
LIMIT $1 OFFSET $2
`

type ListGlobalFeedParams struct {
	Limit  int32
	Offset int32
}

type ListGlobalFeedRow struct {
	UserID         string
	PostID         int32
	Title          string
	Content        string
	LikesCount     int32
	DislikesCount  int32
	CommentsCount  int32
	ViewsCount     int32
	AuthorUsername string
}

// ========================================================
// 3. استعلامات القوائم والـ Feeds (لجلب البيانات للـ ListView)
// ========================================================
// الفيد العام: يجلب كل بوستات التطبيق مجهزة للـ Pagination
func (q *Queries) ListGlobalFeed(ctx context.Context, arg ListGlobalFeedParams) ([]ListGlobalFeedRow, error) {
	rows, err := q.db.Query(ctx, listGlobalFeed, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGlobalFeedRow
	for rows.Next() {
		var i ListGlobalFeedRow
		if err := rows.Scan(
			&i.UserID,
			&i.PostID,
			&i.Title,
			&i.Content,
			&i.LikesCount,
			&i.DislikesCount,
			&i.CommentsCount,
			&i.ViewsCount,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByUser = `-- name: ListPostsByUser :many
SELECT 
    p.user_id, p.post_id, p.title, p.content, 
    p.likes_count, p.dislikes_count, p.comments_count, p.views_count,
    u.username AS author_username
FROM posts AS p
JOIN users AS u ON p.user_id = u.user_id
WHERE p.user_id = $1
ORDER BY p.post_id DESC
`

type ListPostsByUserRow struct {
	UserID         string
	PostID         int32
	Title          string
	Content        string
	LikesCount     int32
	DislikesCount  int32
	CommentsCount  int32
	ViewsCount     int32
	AuthorUsername string
}

// صفحة البروفايل: جلب كل بوستات مستخدم معين من الأحدث للأقدم
func (q *Queries) ListPostsByUser(ctx context.Context, userID string) ([]ListPostsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPostsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByUserRow
	for rows.Next() {
		var i ListPostsByUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.PostID,
			&i.Title,
			&i.Content,
			&i.LikesCount,
			&i.DislikesCount,
			&i.CommentsCount,
			&i.ViewsCount,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET username = $2, password = $3
WHERE user_id = $1
`

type UpdateUserProfileParams struct {
	UserID   string
	Username string
	Password pgtype.Text
}

// تحديث اسم المستخدم أو الباسورد
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile, arg.UserID, arg.Username, arg.Password)
	return err
}
