// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchGetUsersByIDs = `-- name: BatchGetUsersByIDs :many
SELECT id, username, name, description, followers, following, point, posts_count, city
FROM users
WHERE id = ANY($1::bigint[])
ORDER BY ARRAY_POSITION($1::bigint[], id)
`

type BatchGetUsersByIDsRow struct {
	ID          int64
	Username    string
	Name        string
	Description pgtype.Text
	Followers   pgtype.Int4
	Following   pgtype.Int4
	Point       pgtype.Int4
	PostsCount  pgtype.Int4
	City        pgtype.Text
}

// كويري عالي الأداء لتطبيقات الـ Production: تمرر له مصفوفة IDs (مثال: [5, 12, 90])
// ليعيد لك بياناتهم كاملة بطلب واحد (Single Round-Trip)، مفيد جداً عند عرض كتاب المنشورات أو قوائم الإعجابات
func (q *Queries) BatchGetUsersByIDs(ctx context.Context, dollar_1 []int64) ([]BatchGetUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, batchGetUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchGetUsersByIDsRow
	for rows.Next() {
		var i BatchGetUsersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Description,
			&i.Followers,
			&i.Following,
			&i.Point,
			&i.PostsCount,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    username,
    password,
    email,
    name,
    description,
    city,
    location,
    birth_date
) VALUES (
    LOWER(TRIM($1)), -- حماية: تحويل اسم المستخدم للأحرف الصغيرة وإزالة الفراغات الزائدة
    $2,
    LOWER(TRIM($3)),
    TRIM($4),
    $5,
    $6,
    $7,
    $8
)
RETURNING id, username, email, name, description, followers, following, views, likes_count, point, posts_count, city, location, birth_date, created_at
`

type CreateUserParams struct {
	Btrim       string
	Password    string
	Btrim_2     string
	Btrim_3     string
	Description pgtype.Text
	City        pgtype.Text
	Location    pgtype.Text
	BirthDate   pgtype.Date
}

type CreateUserRow struct {
	ID          int64
	Username    string
	Email       pgtype.Text
	Name        string
	Description pgtype.Text
	Followers   pgtype.Int4
	Following   pgtype.Int4
	Views       pgtype.Int4
	LikesCount  pgtype.Int4
	Point       pgtype.Int4
	PostsCount  pgtype.Int4
	City        pgtype.Text
	Location    pgtype.Text
	BirthDate   pgtype.Date
	CreatedAt   pgtype.Timestamp
}

// ====================================================================================
// 1. العمليات الأساسية وإدارة الحساب والأمان (Core CRUD & Authentication)
// ====================================================================================
// إنشاء حساب مستخدم جديد كلياً مع تصفير العدادات تلقائياً وإرجاع البيانات الأساسية فوراً
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Btrim,
		arg.Password,
		arg.Btrim_2,
		arg.Btrim_3,
		arg.Description,
		arg.City,
		arg.Location,
		arg.BirthDate,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Description,
		&i.Followers,
		&i.Following,
		&i.Views,
		&i.LikesCount,
		&i.Point,
		&i.PostsCount,
		&i.City,
		&i.Location,
		&i.BirthDate,
		&i.CreatedAt,
	)
	return i, err
}

const decrementUserFollowers = `-- name: DecrementUserFollowers :exec
UPDATE users 
SET followers = GREATEST(0, followers - 1) 
WHERE id = $1
`

// إنقاص عدد المتابعين بمقدار 1 مع حماية برمجية صارمة `GREATEST(0, ...)` تمنع نزول العداد تحت الصفر نهائياً
func (q *Queries) DecrementUserFollowers(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementUserFollowers, id)
	return err
}

const decrementUserFollowing = `-- name: DecrementUserFollowing :exec
UPDATE users 
SET following = GREATEST(0, following - 1) 
WHERE id = $1
`

// إنقاص عدد الحسابات التي يتابعها المستخدم الحالي بمقدار 1 مع الحماية من الأرقام السالبة
func (q *Queries) DecrementUserFollowing(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementUserFollowing, id)
	return err
}

const decrementUserPostsCount = `-- name: DecrementUserPostsCount :exec
UPDATE users 
SET posts_count = GREATEST(0, posts_count - 1) 
WHERE id = $1
`

// إنقاص عداد المنشورات عند قيام المستخدم بحذف أحد منشوراته مع ضمان عدم النزول تحت الصفر
func (q *Queries) DecrementUserPostsCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementUserPostsCount, id)
	return err
}

const discoverPopularUsersByCity = `-- name: DiscoverPopularUsersByCity :many
SELECT id, username, name, description, followers, point, city
FROM users
WHERE city = $1 AND id != $2
ORDER BY point DESC, followers DESC
LIMIT $3 OFFSET $4
`

type DiscoverPopularUsersByCityParams struct {
	City   pgtype.Text
	ID     int64
	Limit  int32
	Offset int32
}

type DiscoverPopularUsersByCityRow struct {
	ID          int64
	Username    string
	Name        string
	Description pgtype.Text
	Followers   pgtype.Int4
	Point       pgtype.Int4
	City        pgtype.Text
}

// نظام الاقتراحات المحلي: جلب وتصفية الحسابات الأكثر شهرة المتواجدة في نفس مدينة المستخدم الحالي لاستكشافهم
func (q *Queries) DiscoverPopularUsersByCity(ctx context.Context, arg DiscoverPopularUsersByCityParams) ([]DiscoverPopularUsersByCityRow, error) {
	rows, err := q.db.Query(ctx, discoverPopularUsersByCity,
		arg.City,
		arg.ID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverPopularUsersByCityRow
	for rows.Next() {
		var i DiscoverPopularUsersByCityRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Description,
			&i.Followers,
			&i.Point,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, email, name, description, followers, following, views, likes_count, point, posts_count, city, location, birth_date, created_at
FROM users
WHERE id = $1
`

// جلب كامل بيانات المستخدم بواسطة المعرف الفريد الداخلي (ID)
func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Name,
		&i.Description,
		&i.Followers,
		&i.Following,
		&i.Views,
		&i.LikesCount,
		&i.Point,
		&i.PostsCount,
		&i.City,
		&i.Location,
		&i.BirthDate,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, username, password, email, name
FROM users
WHERE username = LOWER(TRIM($1)) OR email = LOWER(TRIM($1))
LIMIT 1
`

type GetUserByUsernameOrEmailRow struct {
	ID       int64
	Username string
	Password string
	Email    pgtype.Text
	Name     string
}

// كويري تسجيل الدخول الاحترافي: جلب بيانات الحساب بفحص مدمج لاسم المستخدم أو البريد الإلكتروني بطلب واحد
func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, btrim string) (GetUserByUsernameOrEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameOrEmail, btrim)
	var i GetUserByUsernameOrEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const getUsersLeaderboard = `-- name: GetUsersLeaderboard :many



SELECT id, username, name, description, followers, point, posts_count, city
FROM users
ORDER BY point DESC, followers DESC
LIMIT $1 OFFSET $2
`

type GetUsersLeaderboardParams struct {
	Limit  int32
	Offset int32
}

type GetUsersLeaderboardRow struct {
	ID          int64
	Username    string
	Name        string
	Description pgtype.Text
	Followers   pgtype.Int4
	Point       pgtype.Int4
	PostsCount  pgtype.Int4
	City        pgtype.Text
}

// يحافظ على نفس ترتيب الـ IDs الممررة تماماً
// ====================================================================================
// 3. أنظمة الاستكشاف ولوحة الصدارة (Discovery & Gamification Leaderboards)
// ====================================================================================
// لوحة الصدارة للمنصة: جلب الحسابات الأكثر تفاعلاً وشهرة بناءً على حقل النقاط (point) أو عدد المتابعين مع الـ Pagination
func (q *Queries) GetUsersLeaderboard(ctx context.Context, arg GetUsersLeaderboardParams) ([]GetUsersLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getUsersLeaderboard, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersLeaderboardRow
	for rows.Next() {
		var i GetUsersLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Description,
			&i.Followers,
			&i.Point,
			&i.PostsCount,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementUserFollowers = `-- name: IncrementUserFollowers :exec
UPDATE users 
SET followers = followers + 1 
WHERE id = $1
`

// زيادة عدد المتابعين بمقدار 1 للحساب المتلقّي للمتابعة
func (q *Queries) IncrementUserFollowers(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementUserFollowers, id)
	return err
}

const incrementUserFollowing = `-- name: IncrementUserFollowing :exec
UPDATE users 
SET following = following + 1 
WHERE id = $1
`

// زيادة عدد الحسابات التي يتابعها المستخدم الحالي بمقدار 1
func (q *Queries) IncrementUserFollowing(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementUserFollowing, id)
	return err
}

const incrementUserPostsCount = `-- name: IncrementUserPostsCount :exec
UPDATE users 
SET posts_count = posts_count + 1 
WHERE id = $1
`

// زيادة عداد المنشورات للمستخدم فور قيامه بنشر محتوى جديد بنجاح
func (q *Queries) IncrementUserPostsCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementUserPostsCount, id)
	return err
}

const incrementUserViews = `-- name: IncrementUserViews :exec

UPDATE users 
SET views = views + 1 
WHERE id = $1
`

// ====================================================================================
// 4. إدارة العدادات الذرية الذكية (Safe Atomic Counters Operations)
// ====================================================================================
// زيادة عداد مشاهدات الملف الشخصي بشكل ذري (Atomic) لمنع مشكلة تضارب البيانات (Race Conditions) عند تصفح البروفايل
func (q *Queries) IncrementUserViews(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementUserViews, id)
	return err
}

const searchUsersAdvanced = `-- name: SearchUsersAdvanced :many

SELECT id, username, name, description, followers, following, views, likes_count, point, posts_count, city, location, created_at
FROM users
WHERE ($1::text = '' OR username ILIKE '%' || $1 || '%' OR name ILIKE '%' || $1 || '%' OR description ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR city ILIKE $2)
  AND (point >= $3::int)
  AND (followers >= $4::int)
ORDER BY point DESC, followers DESC, created_at DESC
LIMIT $5 OFFSET $6
`

type SearchUsersAdvancedParams struct {
	Column1 string
	Column2 string
	Column3 int32
	Column4 int32
	Limit   int32
	Offset  int32
}

type SearchUsersAdvancedRow struct {
	ID          int64
	Username    string
	Name        string
	Description pgtype.Text
	Followers   pgtype.Int4
	Following   pgtype.Int4
	Views       pgtype.Int4
	LikesCount  pgtype.Int4
	Point       pgtype.Int4
	PostsCount  pgtype.Int4
	City        pgtype.Text
	Location    pgtype.Text
	CreatedAt   pgtype.Timestamp
}

// ====================================================================================
// 2. كويريات جلب القوائم والبحث المتقدم متعدد الحالات (Advanced Dynamic Search & Batch)
// ====================================================================================
// كويري البحث الذهبي (Multi-Criteria Filter): كويري مكثف يقبل عدة حالات في نفس الوقت!
// يبحث بالنص (Fuzzy Search) في (الاسم، اليوزر، الوصف) ويقوم بالفلترة حسب المدينة، ويشترط حداً أدنى من النقاط أو المتابعين
// إذا تم تمرير قيم فارغة أو صفرية، يتجاهل الكويري الشرط تلقائياً، مع دعم كامل للـ Pagination لضمان سرعة السيرفر
func (q *Queries) SearchUsersAdvanced(ctx context.Context, arg SearchUsersAdvancedParams) ([]SearchUsersAdvancedRow, error) {
	rows, err := q.db.Query(ctx, searchUsersAdvanced,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersAdvancedRow
	for rows.Next() {
		var i SearchUsersAdvancedRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Description,
			&i.Followers,
			&i.Following,
			&i.Views,
			&i.LikesCount,
			&i.Point,
			&i.PostsCount,
			&i.City,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPasswordSecure = `-- name: UpdateUserPasswordSecure :exec
UPDATE users
SET password = $2
WHERE id = $1
`

type UpdateUserPasswordSecureParams struct {
	ID       int64
	Password string
}

// تحديث كلمة المرور بشكل منفصل لرفع مستوى الحماية والأمان في السيرفر
func (q *Queries) UpdateUserPasswordSecure(ctx context.Context, arg UpdateUserPasswordSecureParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordSecure, arg.ID, arg.Password)
	return err
}

const updateUserPoints = `-- name: UpdateUserPoints :exec
UPDATE users 
SET point = point + $2 
WHERE id = $1
`

type UpdateUserPointsParams struct {
	ID    int64
	Point pgtype.Int4
}

// التحكم بنقاط المستخدم (Gamification System): مرر قيمة موجبة لزيادة نقاطه (عند النشر/التفاعل) أو سالبة لخصمها
func (q *Queries) UpdateUserPoints(ctx context.Context, arg UpdateUserPointsParams) error {
	_, err := q.db.Exec(ctx, updateUserPoints, arg.ID, arg.Point)
	return err
}

const updateUserProfileSecure = `-- name: UpdateUserProfileSecure :one
UPDATE users
SET
    name = TRIM($2),
    description = $3,
    city = $4,
    location = $5,
    birth_date = $6
WHERE id = $1
RETURNING id, username, email, name, description, city, location, birth_date
`

type UpdateUserProfileSecureParams struct {
	ID          int64
	Btrim       string
	Description pgtype.Text
	City        pgtype.Text
	Location    pgtype.Text
	BirthDate   pgtype.Date
}

type UpdateUserProfileSecureRow struct {
	ID          int64
	Username    string
	Email       pgtype.Text
	Name        string
	Description pgtype.Text
	City        pgtype.Text
	Location    pgtype.Text
	BirthDate   pgtype.Date
}

// تحديث الملف الشخصي بشكل آمن ومباشر مع إرجاع الصف المحدث لتحديث واجهة المستخدم (UI State)
func (q *Queries) UpdateUserProfileSecure(ctx context.Context, arg UpdateUserProfileSecureParams) (UpdateUserProfileSecureRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfileSecure,
		arg.ID,
		arg.Btrim,
		arg.Description,
		arg.City,
		arg.Location,
		arg.BirthDate,
	)
	var i UpdateUserProfileSecureRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Description,
		&i.City,
		&i.Location,
		&i.BirthDate,
	)
	return i, err
}
